-- Ejecutar UNA VEZ sobre una copia de la base PostgreSQL existente.
-- No elimina ni modifica datos de las tablas existentes.
BEGIN;
LOCK TABLE roles IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO roles (id_rol, nombre, descripcion, activo)
SELECT (SELECT COALESCE(MAX(id_rol),0)+1 FROM roles),
       'Asesor comercial interno', 'Equipo comercial de la plataforma COMI', TRUE
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE nombre = 'Asesor comercial interno');
SELECT setval(pg_get_serial_sequence('roles','id_rol'), (SELECT MAX(id_rol) FROM roles), true);

CREATE TABLE comercial_prospectos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    id_asesor INTEGER,
    estado VARCHAR(30) NOT NULL DEFAULT 'nuevo'
        CHECK (estado IN ('nuevo','asignado','en_seguimiento','cotizacion_enviada','contratado','no_interesado')),
    proximo_contacto TIMESTAMPTZ,
    id_empresa_contratada INTEGER REFERENCES empresas(id_empresa),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_empresa, id_cliente),
    FOREIGN KEY (id_empresa,id_cliente) REFERENCES clientes(id_empresa,id_cliente),
    FOREIGN KEY (id_empresa,id_asesor) REFERENCES usuarios(id_empresa,id_usuario),
    CHECK (estado <> 'contratado' OR id_empresa_contratada IS NOT NULL),
    CHECK (id_empresa_contratada IS NULL OR id_empresa_contratada <> id_empresa)
);
CREATE INDEX comercial_asesor_agenda ON comercial_prospectos(id_empresa,id_asesor,proximo_contacto);
CREATE TABLE comercial_seguimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prospecto BIGINT NOT NULL REFERENCES comercial_prospectos(id),
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    tipo VARCHAR(30) NOT NULL,
    nota TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL,
    proximo_contacto TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX comercial_historial ON comercial_seguimientos(id_prospecto,created_at DESC);
COMMIT;
