@extends('comercial.base')
@section('commercial-title', $prospecto->organizacion ?: $prospecto->nombre.' '.$prospecto->apellido_paterno)
@section('commercial-subtitle', 'Conversaciones de COMI y seguimiento del equipo comercial.')
@section('commercial-content')
<div class="head"><a href="{{ route('comercial.prospectos.index') }}">← Volver a prospectos</a><span class="badge {{ $prospecto->estado }}">{{ \App\Support\Comercial::ESTADOS[$prospecto->estado] }}</span></div>
<div class="split"><div>
    <section class="card"><h2>Información de contacto</h2><div class="grid space"><div><small>Persona de contacto</small><p>{{ $prospecto->nombre }} {{ $prospecto->apellido_paterno }}</p></div><div><small>Teléfono</small><p>{{ $prospecto->telefono_principal }}</p></div><div><small>Correo</small><p>{{ $prospecto->correo ?: 'No proporcionado' }}</p></div><div><small>Asesor responsable</small><p>{{ $prospecto->asesor_nombre ? $prospecto->asesor_nombre.' '.$prospecto->asesor_apellido : 'Sin asignar' }}</p></div></div>
    @if($prospecto->proximo_contacto)<p class="note">Próximo contacto: {{ \Carbon\Carbon::parse($prospecto->proximo_contacto)->timezone(config('app.timezone'))->format('d/m/Y H:i') }} · {{ config('app.timezone') }}</p>@endif
    @if($prospecto->id_empresa_contratada)<p class="note">Contratación vinculada a la empresa #{{ $prospecto->id_empresa_contratada }}.</p>@endif
    </section>
    <section class="card"><h2>Necesidades identificadas por COMI</h2>
    @if($calificacion)<div class="grid space">@foreach(['giro'=>'Giro','numero_colaboradores'=>'Colaboradores','canal_principal'=>'Canal principal','volumen_estimado'=>'Volumen estimado','presupuesto_aproximado'=>'Presupuesto indicado por el prospecto','objetivo_principal'=>'Objetivo principal'] as $campo=>$etiqueta)<div><small>{{ $etiqueta }}</small><p>{{ $calificacion->$campo ?: 'No proporcionado' }}</p></div>@endforeach</div>@else<p class="muted">Todavía no hay una calificación estructurada para este prospecto.</p>@endif
    <p class="note">COMI recopila información. La cotización y el contacto comercial los realiza el asesor.</p></section>
    <section class="card"><h2>Interacciones de COMI</h2>
    @forelse($interacciones as $i)<details><summary>{{ \Carbon\Carbon::parse($i->fecha_hora_inicio)->timezone(config('app.timezone'))->format('d/m/Y H:i') }} · {{ $i->intencion ?: 'Conversación' }} · Interés {{ $i->nivel_interes ?: 'sin clasificar' }}</summary><p class="muted space">{{ $i->cita_solicitada ? 'Solicitó una cita.' : 'Sin solicitud de cita registrada.' }}</p><h3 class="space">Transcripción</h3><pre>{{ $i->transcripcion ?: 'Sin transcripción disponible.' }}</pre><h3 class="space">Respuesta registrada</h3><pre>{{ $i->respuesta ?: 'Sin respuesta registrada.' }}</pre></details>@empty<p class="empty">Sin interacciones disponibles.</p>@endforelse
    @include('comercial.paginacion', ['pagina' => $interacciones])</section>
    <section class="card"><h2>Historial de seguimiento</h2>
    @forelse($historial as $s)<article class="history"><small>{{ \Carbon\Carbon::parse($s->created_at)->timezone(config('app.timezone'))->format('d/m/Y H:i') }} · {{ $s->nombre }} {{ $s->apellido_paterno }}</small><h3 class="space">{{ ucfirst(str_replace('_',' ',$s->tipo)) }} · {{ \App\Support\Comercial::ESTADOS[$s->estado] }}</h3><p>{{ $s->nota }}</p>@if($s->proximo_contacto)<small>Contacto programado: {{ \Carbon\Carbon::parse($s->proximo_contacto)->timezone(config('app.timezone'))->format('d/m/Y H:i') }}</small>@endif</article>@empty<p class="empty">El seguimiento comercial aún no ha comenzado.</p>@endforelse
    @include('comercial.paginacion', ['pagina' => $historial])</section>
</div><aside>
@if((int) Auth::user()->id_rol === 1 && !in_array($prospecto->estado, ['contratado','no_interesado']))
<section class="card"><h2>Asignar responsable</h2><form method="POST" action="{{ route('comercial.asignar', $prospecto->id) }}">@csrf @method('PUT')<div class="field"><label for="id_asesor">Asesor interno activo</label><select id="id_asesor" name="id_asesor" required><option value="">Seleccionar asesor</option>@foreach($asesores as $a)<option value="{{ $a->id_usuario }}" @selected((string) old('id_asesor', $prospecto->id_asesor) === (string) $a->id_usuario)>{{ $a->nombre }} {{ $a->apellido_paterno }}</option>@endforeach</select></div><button class="btn primary">Guardar asignación</button></form></section>
@endif
@if($prospecto->estado !== 'contratado')
<section class="card"><h2>Registrar seguimiento</h2><p class="muted">Registra el resultado de tu contacto. Este formulario no inicia una llamada telefónica.</p><form class="space" method="POST" action="{{ route('comercial.seguimientos.store', $prospecto->id) }}">@csrf
<div class="field"><label for="tipo">Medio de contacto</label><select name="tipo" id="tipo" required>@foreach(['llamada_manual'=>'Llamada registrada manualmente','correo'=>'Correo','whatsapp'=>'WhatsApp','nota'=>'Nota interna'] as $v=>$t)<option value="{{ $v }}" @selected(old('tipo') === $v)>{{ $t }}</option>@endforeach</select></div>
<div class="field"><label for="nota">Resultado y observaciones</label><textarea name="nota" id="nota" maxlength="5000" required placeholder="Qué se conversó, qué necesita y cuál es el siguiente paso…">{{ old('nota') }}</textarea></div>
<div class="field"><label for="estado">Estado comercial</label><select name="estado" id="estado" required>@foreach(['en_seguimiento','cotizacion_enviada','no_interesado'] as $v)<option value="{{ $v }}" @selected(old('estado', $prospecto->estado) === $v)>{{ \App\Support\Comercial::ESTADOS[$v] }}</option>@endforeach</select></div>
<div class="field"><label for="proximo_contacto">Próximo contacto (opcional)</label><input type="datetime-local" id="proximo_contacto" name="proximo_contacto" value="{{ old('proximo_contacto', $prospecto->proximo_contacto && \Carbon\Carbon::parse($prospecto->proximo_contacto)->isFuture() ? \Carbon\Carbon::parse($prospecto->proximo_contacto)->timezone(config('app.timezone'))->format('Y-m-d\TH:i') : '') }}"><small>Horario {{ config('app.timezone') }}. Vacío elimina la fecha pendiente; “No interesado” también la cancela.</small></div><button class="btn primary">Guardar seguimiento</button></form></section>
@if((int) Auth::user()->id_rol === 1)
<section class="card"><h2>Confirmar contratación</h2><p class="muted">Primero registra la empresa en el apartado Empresas; después vincúlala aquí. Esta acción cierra el seguimiento.</p><form class="space" method="POST" action="{{ route('comercial.contratar', $prospecto->id) }}" onsubmit="return confirm('¿Confirmar la contratación y cerrar este prospecto?');">@csrf<div class="field"><label for="id_empresa_contratada">Empresa contratante</label><select name="id_empresa_contratada" id="id_empresa_contratada" required><option value="">Selecciona una empresa</option>@foreach($empresas as $e)<option value="{{ $e->id_empresa }}" @selected((string) old('id_empresa_contratada') === (string) $e->id_empresa)>{{ $e->nombre }}</option>@endforeach</select></div><div class="field"><label for="nota_contrato">Referencia o detalle del acuerdo</label><textarea name="nota" id="nota_contrato" maxlength="5000" required>{{ old('nota') }}</textarea></div><button class="btn">Confirmar contratación</button></form></section>
@endif
@endif
</aside></div>
@endsection
